name: odata_client
description: An OData Client for Dart
version: 0.0.1
author: Mabenan
homepage: https://github.com/Mabenan

publish_to: pub

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  http: ^0.13.3
  mutex: ^3.0.0
  xml: ^5.1.0

dev_dependencies:
  test: ^1.17.3
  mockito: ^5.0.7
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

